### ISSUE TITLE
After "import pyonmttok"， torch will report ERROR "Segmentation fault (core dumped) "

### ISSUE THREAD

**Issue by areaChun** [OpenNMT/Tokenizer#293] opened 2022-08-18 06:47 UTC
non pyonmttok:
![image](https://user-images.githubusercontent.com/9265549/185315668-cbd4e5ed-2c1c-482c-8ca6-cc207d9edc20.png)

with pyonmttok:
![image](https://user-images.githubusercontent.com/9265549/185315868-25ad0a1b-c222-420b-b509-360982c22772.png)

**Comment by guillaumekln** [comment] 2022-08-20 08:16
Can you try changing the import order and see if it makes a difference?

```python
import torch
import pyonmttok
```

**Comment by guillaumekln** [comment] 2022-09-12 08:01
The issue is fixed by this commit https://github.com/OpenNMT/Tokenizer/commit/372a530079f47cf36f218f13c3f613416a779dec which updates the Python build environment to `manylinux2014`.

**Closed by guillaumekln** 2022-09-12 08:01 UTC
